import { ReactNode } from 'react';
import { Image,SafeAreaView,ScrollView,StyleSheet,Text,TextInput,TouchableOpacity,View } from 'react-native';
export const color={ink:'#0b1728',blue:'#137fe9',muted:'#637389',line:'#dce5ef',bg:'#f5f8fc'};
export function Screen({children}:{children:ReactNode}){return <SafeAreaView style={{flex:1,backgroundColor:color.bg}}><ScrollView contentContainerStyle={{padding:22,paddingBottom:80}} keyboardShouldPersistTaps="handled"><View style={styles.brand}><Image source={require('../../assets/icon.png')} style={{width:55,height:55,borderRadius:12}} /><Text style={{fontSize:17,fontWeight:'800',color:color.ink}}>BUENOS AIRES{'\n'}AL POR MAYOR</Text></View>{children}</ScrollView></SafeAreaView>}
export function Title({children}:{children:ReactNode}){return <Text style={styles.title}>{children}</Text>}
export function Body({children}:{children:ReactNode}){return <Text style={styles.body}>{children}</Text>}
export function Card({children}:{children:ReactNode}){return <View style={styles.card}>{children}</View>}
export function Button({children,onPress,disabled=false,secondary=false}:{children:ReactNode;onPress:()=>void;disabled?:boolean;secondary?:boolean}){return <TouchableOpacity disabled={disabled} onPress={onPress} style={[styles.button,secondary&&styles.secondary,disabled&&{opacity:.5}]}><Text style={[styles.buttonText,secondary&&{color:color.blue}]}>{children}</Text></TouchableOpacity>}
export function Field({label,value,onChangeText,placeholder,multiline=false,secureTextEntry=false,keyboardType='default'}:{label:string;value:string;onChangeText:(v:string)=>void;placeholder?:string;multiline?:boolean;secureTextEntry?:boolean;keyboardType?:'default'|'email-address'|'phone-pad'|'numeric'|'url'}){return <View style={{marginBottom:17}}><Text style={styles.label}>{label}</Text><TextInput value={value} onChangeText={onChangeText} placeholder={placeholder} multiline={multiline} secureTextEntry={secureTextEntry} keyboardType={keyboardType} autoCapitalize={keyboardType==='email-address'||keyboardType==='url'?'none':'sentences'} style={[styles.input,multiline&&{minHeight:108,textAlignVertical:'top'}]} /></View>}
export const styles=StyleSheet.create({brand:{flexDirection:'row',alignItems:'center',gap:12,marginBottom:27},title:{fontSize:31,fontWeight:'900',color:color.ink,marginBottom:12},body:{color:color.muted,fontSize:15,lineHeight:23,marginBottom:18},card:{backgroundColor:'white',borderWidth:1,borderColor:color.line,borderRadius:18,padding:20,marginBottom:16},button:{backgroundColor:color.blue,padding:16,borderRadius:11,alignItems:'center',marginTop:10},secondary:{backgroundColor:'#e7f2ff'},buttonText:{color:'white',fontWeight:'800',fontSize:15},label:{color:color.ink,fontWeight:'700',marginBottom:7},input:{backgroundColor:'white',borderColor:'#c9d5e3',borderWidth:1,borderRadius:10,padding:13,fontSize:16,color:color.ink}});
