'use client';
import { useCallback, useEffect, useState } from 'react';

type Quote = { id:string; category:string; description:string; quantity:number; status:string; item_price:string|null; shipping_price:string|null; quote_note:string|null; quote_expires_at:string|null; tracking:string|null; created_at:string };
const labels:Record<string,string> = {requested:'Esperando cotización',quoted:'Cotización disponible',payment_pending:'Pago pendiente de confirmación',paid:'Pagado',preparing:'En preparación',shipped:'Enviado',delivered:'Entregado',cancelled:'Cancelado'};
const money=(n:number)=>new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS'}).format(n);

export default function CotizarPage() {
  const [quotes,setQuotes]=useState<Quote[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[logged,setLogged]=useState<boolean|null>(null);
  const load=useCallback(async()=>{try{const r=await fetch('/api/quotes',{cache:'no-store'});if(r.status===401){setLogged(false);return}if(!r.ok)throw new Error('No pudimos cargar tus solicitudes.');setLogged(true);setQuotes((await r.json()).quotes)}catch(e){setError(e instanceof Error?e.message:'Ocurrió un error.')}},[]);
  useEffect(()=>{void load()},[load]);
  async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setError('');setBusy(true);const form=e.currentTarget;const data=Object.fromEntries(new FormData(form));try{const r=await fetch('/api/quotes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const body=await r.json();if(!r.ok)throw new Error(body.error);form.reset();await load()}catch(e){setError(e instanceof Error?e.message:'No se pudo enviar.')}finally{setBusy(false)}}
  async function accept(id:string){setError('');setBusy(true);try{const r=await fetch(`/api/quotes/${id}/accept`,{method:'POST'});const body=await r.json();if(!r.ok)throw new Error(body.error);window.location.assign(body.checkoutUrl)}catch(e){setError(e instanceof Error?e.message:'No se pudo iniciar el pago.');setBusy(false)}}
  return <main className="quotePage"><a href="/" className="quoteBack">← Buenos Aires al por mayor</a><div className="quoteIntro"><img src="/brand-logo-wide.svg" alt="Buenos Aires al por mayor" /><span className="eyebrow dark">Pedidos a medida</span><h1>Pedí lo que necesitás. Te lo cotizamos.</h1><p>Describí el producto. Revisá nuestra propuesta, aceptala y pagá con Mercado Pago. Seguí el envío desde tu cuenta.</p></div>
    {logged===false?<div className="quoteCard"><h2>Ingresá para continuar</h2><p>Tus solicitudes y cotizaciones quedan asociadas a tu cuenta.</p><a href="/login?next=/cotizar" className="button button-primary">Ingresar</a> <a href="/registro" className="button">Crear cuenta</a></div>:logged===null?<p>Cargando tus solicitudes…</p>:<><form className="quoteCard quoteForm" onSubmit={submit}><h2>Nueva solicitud</h2><div className="quoteFields"><label>Categoría<select name="category" required><option value="">Seleccionar</option>{['Ropa','Accesorios','Repuestos para celulares','Electrodomésticos','Tecnología','Otro'].map(x=><option key={x}>{x}</option>)}</select></label><label>Cantidad<input name="quantity" type="number" min="1" max="100000" defaultValue="1" required /></label></div><label>¿Qué producto buscás?<textarea name="description" minLength={8} maxLength={2000} required placeholder="Marca, modelo, talle, color y detalles" /></label><label>Enlace de referencia (opcional)<input name="referenceUrl" type="url" maxLength={500} placeholder="https://..." /></label><div className="quoteFields"><label>WhatsApp<input name="phone" type="tel" required placeholder="+54 9 ..." /></label><label>Dirección de entrega<input name="deliveryAddress" required minLength={8} maxLength={300} placeholder="Calle, número, localidad y provincia" /></label></div><button className="button button-primary" disabled={busy}>Solicitar cotización</button></form>
    <section className="quoteList"><h2>Mis solicitudes</h2>{quotes.length===0?<p>Aún no tenés solicitudes.</p>:quotes.map(q=><article className="quoteCard" key={q.id}><div className="quoteTop"><strong>{q.category} · {q.quantity} unidad(es)</strong><span>{labels[q.status]||q.status}</span></div><p>{q.description}</p><small>Pedido #{q.id.slice(0,8)} · {new Date(q.created_at).toLocaleDateString('es-AR')}</small>{q.item_price!==null&&<div className="quotePrice"><strong>Total: {money(Number(q.item_price)+Number(q.shipping_price))}</strong><small>Productos {money(Number(q.item_price))} · Envío {money(Number(q.shipping_price))}</small><small>Válida hasta {q.quote_expires_at?new Date(q.quote_expires_at).toLocaleString('es-AR'):'—'}</small></div>}{q.quote_note&&<p>Nota: {q.quote_note}</p>}{q.tracking&&<p>Seguimiento: {q.tracking}</p>}{q.status==='quoted'&&<button className="button button-primary" disabled={busy||!!q.quote_expires_at&&new Date(q.quote_expires_at)<=new Date()} onClick={()=>void accept(q.id)}>Aceptar y pagar con Mercado Pago</button>}{q.status==='payment_pending'&&<p>Estamos verificando el pago con Mercado Pago. Actualizá esta página en unos minutos.</p>}</article>)}</section></>}
    {error&&<p role="alert" className="quoteError">{error}</p>}</main>;
}
