import { useCallback,useState } from 'react';
import { router,useFocusEffect,useLocalSearchParams } from 'expo-router';
import * as WebBrowser from 'expo-web-browser';
import { ActivityIndicator,Text,View } from 'react-native';
import { useAuth } from '../../lib/auth';
import { api,money,Quote,statusLabel } from '../../lib/api';
import { Body,Button,Card,color,Screen,Title } from '../../components/UI';
const steps=['requested','quoted','payment_pending','paid','preparing','shipped','delivered'];
export default function Pedido(){const {id}=useLocalSearchParams<{id:string}>(),{token}=useAuth();const [quote,setQuote]=useState<Quote|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);const load=useCallback(async()=>{if(!token)return;try{const result=await api<{quotes:Quote[]}>('/api/quotes',token);setQuote(result.quotes.find(q=>q.id===id)||null)}catch(e){setError(e instanceof Error?e.message:'No se pudo cargar.')}},[token,id]);useFocusEffect(useCallback(()=>{void load()},[load]));async function pay(){if(!quote)return;setBusy(true);setError('');try{const result=await api<{checkoutUrl:string}>(`/api/quotes/${quote.id}/accept`,token,{method:'POST'});await WebBrowser.openBrowserAsync(result.checkoutUrl);await load()}catch(e){setError(e instanceof Error?e.message:'No se pudo iniciar el pago.')}finally{setBusy(false)}}return <Screen><Text onPress={()=>router.back()} style={{color:color.blue,marginBottom:24}}>← Mis pedidos</Text>{!quote?<ActivityIndicator />:<><Title>{quote.category}</Title><Body>Pedido #{quote.id.slice(0,8)} · {quote.quantity} unidad(es)</Body><Card><Text style={{fontWeight:'800',fontSize:18}}>{statusLabel[quote.status]||quote.status}</Text><Text style={{color:color.muted,marginTop:12,lineHeight:22}}>{quote.description}</Text>{quote.quote_note?<Text style={{marginTop:14}}>Nota: {quote.quote_note}</Text>:null}</Card><Card><Text style={{fontSize:19,fontWeight:'800',marginBottom:14}}>Avance</Text>{steps.map((step,index)=><View key={step} style={{flexDirection:'row',gap:12,marginBottom:13,alignItems:'center'}}><Text style={{color:steps.indexOf(quote.status)>=index?color.blue:'#a7b6c5',fontWeight:'900'}}>●</Text><Text style={{color:steps.indexOf(quote.status)>=index?color.ink:color.muted}}>{statusLabel[step]}</Text></View>)}</Card>{quote.item_price!==null?<Card><Text style={{fontSize:23,fontWeight:'900'}}>Total {money(Number(quote.item_price)+Number(quote.shipping_price))}</Text><Text style={{color:color.muted,marginTop:8}}>Productos {money(Number(quote.item_price))} · Envío {money(Number(quote.shipping_price))}</Text><Text style={{color:color.muted,marginTop:8}}>Válida hasta {quote.quote_expires_at?new Date(quote.quote_expires_at).toLocaleString('es-AR'):'—'}</Text>{quote.status==='quoted'?<Button disabled={busy||!!quote.quote_expires_at&&new Date(quote.quote_expires_at)<=new Date()} onPress={()=>void pay()}>Aceptar y pagar con Mercado Pago</Button>:null}{quote.status==='payment_pending'?<Body>El pago se confirma al recibir la respuesta de Mercado Pago. Actualizá este pedido después de pagar.</Body>:null}</Card>:null}{quote.tracking?<Card><Text style={{fontWeight:'800'}}>Seguimiento del envío</Text><Text style={{marginTop:8}}>{quote.tracking}</Text></Card>:null}<Button secondary onPress={()=>void load()}>Actualizar estado</Button></>}{error?<Text style={{color:'#b42318'}}>{error}</Text>:null}</Screen>}
