import { products, categories } from '@/lib/catalog';
import { BUSINESS_CONTACT } from '@/lib/business';
import { AddToCartButton } from '@/components/AddToCartButton';

export default function Home() {
  return <main style={{minHeight:'100vh',background:'#f7f7f5',color:'#111'}}>
    <header style={{padding:'20px 6%',display:'flex',justifyContent:'space-between',alignItems:'center',background:'#fff',borderBottom:'1px solid #e8e8e8',position:'sticky',top:0,zIndex:10}}><strong style={{fontSize:22}}>Buenos Aires al por mayor</strong><nav style={{display:'flex',gap:20,fontSize:14,alignItems:'center'}}><a href="#catalogo">Catálogo</a><a href="/proveedores-once">Proveedores</a><a href="/registro">Crear cuenta</a><a href="/login">Ingresar</a><a href="/carrito">🛒 Carrito</a></nav></header>
    <section style={{padding:'80px 6%',background:'#111',color:'#fff'}}><div style={{maxWidth:850}}><p style={{textTransform:'uppercase',letterSpacing:3,fontSize:12}}>Marketplace mayorista · Buenos Aires</p><h1 style={{fontSize:'clamp(42px,7vw,78px)',lineHeight:1.02,margin:'18px 0'}}>Todo el mayorista. En un solo lugar.</h1><p style={{fontSize:19,lineHeight:1.6,color:'#d5d5d5',maxWidth:680}}>Accesorios y repuestos para celulares, con atención centralizada por Buenos Aires al por mayor.</p><a href="#catalogo" style={{display:'inline-block',marginTop:28,padding:'14px 22px',background:'#fff',color:'#111',borderRadius:8,fontWeight:700}}>Explorar catálogo</a></div></section>
    <section id="categorias" style={{padding:'55px 6% 25px'}}><h2>Categorías</h2><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:16,marginTop:22}}>{categories.map(c=><a href="#catalogo" key={c} style={{padding:20,background:'#fff',border:'1px solid #e5e5e5',borderRadius:12,textDecoration:'none',color:'#111'}}><strong>{c}</strong><p style={{color:'#666',marginBottom:0}}>Ver productos →</p></a>)}</div></section>
    <section id="catalogo" style={{padding:'30px 6% 75px'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'end',gap:20}}><div><p style={{textTransform:'uppercase',letterSpacing:2,fontSize:11}}>Catálogo V1</p><h2>Accesorios y repuestos</h2></div><a href="/carrito">Ver carrito →</a></div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(210px,1fr))',gap:16,marginTop:22}}>{products.map(p=><article key={p.id} style={{background:'#fff',border:'1px solid #e5e5e5',borderRadius:14,padding:22}}><div style={{height:130,background:'#eee',borderRadius:10,display:'grid',placeItems:'center',color:'#777'}}>📱</div><p style={{fontSize:12,color:'#777',marginBottom:5}}>{p.category}</p><h3 style={{margin:'5px 0'}}>{p.name}</h3><strong style={{fontSize:20}}>${p.price.toLocaleString('es-AR')}</strong><p style={{fontSize:13,color:'#777'}}>Por {p.unit} · Precio de prueba V1</p><AddToCartButton product={p} /></article>)}</div></section>
    <section style={{padding:'45px 6%',background:'#eaeae6'}}><h2>Atención centralizada</h2><p style={{maxWidth:650,color:'#555'}}>Los proveedores quedan detrás de la plataforma. Vos consultás y hacés el pedido directamente con Buenos Aires al por mayor.</p><a href={BUSINESS_CONTACT.whatsappUrl+'?text='+encodeURIComponent('Hola, quiero consultar por Buenos Aires al por mayor')} target="_blank" rel="noreferrer" style={{display:'inline-block',marginTop:10,padding:'13px 20px',background:'#111',color:'#fff',borderRadius:8}}>Consultar por WhatsApp</a></section>
    <footer id="contacto" style={{padding:'35px 6%',background:'#111',color:'#fff'}}><strong>Buenos Aires al por mayor</strong><div style={{color:'#bbb',lineHeight:1.8,marginTop:8}}><div>WhatsApp: {BUSINESS_CONTACT.whatsappNumber}</div><div>Instagram: {BUSINESS_CONTACT.instagramHandle}</div>{BUSINESS_CONTACT.emails.map(email=><div key={email}>Email: <a href={`mailto:${email}`} style={{color:'#fff'}}>{email}</a></div>)}</div></footer>
  </main>;
}
